services:
  ads-insights:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ads-insights
    ports:
      - '8080:8080'
    depends_on:
      - redis
    env_file:
      - .env.docker
    restart: always
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - '9090:9090'
    networks:
      - app-network

  redis:
    image: redis/redis-stack-server:latest  # You're using redis-stack-server
    restart: always
    ports:
      - "6379:6379"  # Exposes Redis to host machine
    networks:
      - app-network
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    driver: local

networks:
  app-network:
    driver: bridge
